version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: georide_tracker_db
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: pl_password_local_95
      POSTGRES_DB: georide_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
